feat: ktx-config, ktx-print-configs, ktx-list

diff --git a/ktx b/ktx
--- a/ktx
+++ b/ktx
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 
 # Copyright 2017 Heptio Inc.
+# Copyright 2024 Guenter Sandner
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -13,43 +14,156 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
+#
+
+#**********************************************************************
+# ktx-list: list all configs
+#----------------------------------------------------------------------
+ktx-list() {
+  find "${HOME}/.kube/" -maxdepth 1 -type f -exec basename {} \;
+}
+
+###############################################################################################
+# ktx-config: set default kubectl config via ~/.kube/config symbolic link to the given argument
+#      or print the active kubectl config if no argument is given
+#----------------------------------------------------------------------
+ktx-config() {
+  local config="${1}"
+  if [ ! -d "${HOME}/.kube" ]; then
+    mkdir -p "${HOME}/.kube"
+    chmod go-rwx "${HOME}/.kube"
+  fi
+  if [ -z "${config}" -o "${config,,}" = "none" ]; then
+    if [ -n "${KUBECONFIG}" ]; then
+      config=$(echo "${KUBECONFIG}"  | cut -d ':' -f 1)
+      if [ -f "${config}" ]; then
+        config=$(realpath "${config}")
+        if [ $(dirname -- "${config}") = ${HOME}/.kube ]; then
+          basename -- "${config}"
+        else
+          echo "${config}"
+        fi
+        return 0
+      else
+        echo "ERROR: KUBECONFIG '${KUBECONFIG}': '${config}' does not exist" 1>&2
+        return 1
+      fi
+    else
+      if [ -f "${HOME}/.kube/config" ]; then
+        config=$(realpath "${HOME}/.kube/config")
+        basename -- "${config}"
+        return 0
+      fi
+      if [ -h "${HOME}/.kube/config" ]; then
+        echo "ERROR: '${HOME}/.kube/config' is a dangling symbolic link" 1>&2
+        return 1
+      fi
+      if [ -e "${HOME}/.kube/config" ]; then
+        echo "ERROR: '${HOME}/.kube/config' is neither a symbolic link nor a regular file" 1>&2
+        return 1
+      fi
+      return 1
+    fi
+  else
+    if [ -e "${HOME}/.kube/config" -a ! -h "${HOME}/.kube/config" ]; then
+      echo "ERROR: '${HOME}/.kube/config' exists but is not a symbolic link" 1>&2
+      return 1
+    fi
+    rm -f "${HOME}/.kube/config"
+    if [[ "${config}" =~ \/|^config$ ]]; then
+      echo "ERROR: config named '${config}' is not allowed" 1>&2
+      return 1
+    fi
+    if [ ! -f "${HOME}/.kube/${config}" ]; then
+      echo "ERROR: The file '${HOME}/.kube/${config}' does not exist" 1>&2
+      return 1
+    fi
+    if ! ln -s "${config}" "${HOME}/.kube/config"; then
+      echo "ERROR: failed to create symbolic link '${HOME}/.kube/config' to '${HOME}/.kube/${config}'" 1>&2
+      return 1
+    fi
+  fi
+}
+
+###############################################################################################
+# ktx-print-configs: list all configs in ~/.kube
+#----------------------------------------------------------------------
+
+ktx-print-configs() {
+  local active="$(ktx-config)"
+  local default="$(KUBECONFIG='' ktx-config)"
+  if [ -n "${active}" ]; then
+    echo -n "* ${active}"
+    if [ "${active}" = "${default}" ]; then
+      echo " (default)"
+    else
+      echo
+    fi
+  fi
+  while read config; do
+    [ "${config}" != "${active}" ] || continue
+    echo -n "  ${config}"
+    if [ "${config}" = "${default}" ]; then
+      echo " (default)"
+    else
+      echo
+    fi
+  done <<EOT
+$(ktx-list)
+EOT
+
+}
+
+
+###############################################################################################
+# ktx: change kubectl config via KUBECONFIG variable to the given argument
+#   or list available configs if no argument is given
+#----------------------------------------------------------------------
 
 ktx() {
-    # Test that we have a $HOME/.kube to work with
-    if [ ! -d "${HOME}/.kube" ]; then
-        echo "echo \"The following directory does not exist: ${HOME}/.kube. Exiting...\""
-        return 1
-    fi
+  local config="${1}"
+  local configs
 
-    # Verify our $HOME/.kube isn't empty
-    if [ -z "$(ls -A ${HOME}/.kube)" ]; then
-        echo "echo \"No configs present in ${HOME}/.kube. Exiting...\""
-        return 1
-    fi
+  # Test that we have a $HOME/.kube to work with
+  if [ ! -d "${HOME}/.kube" ]; then
+      echo "ERROR: The following directory does not exist: ${HOME}/.kube." 1>&2
+      return 1
+  fi
 
-    # If no argument was given then list the files in $HOME/.kube
-    if [ -z "$1" ]; then
-      for kube in $(find "${HOME}/.kube" -maxdepth 1 -type f -o -type l); do
-        if [[ "${KUBECONFIG}" == "$kube" ]]; then
-          echo -n "(active) "
-        fi
-        echo $(basename "${kube}")
-      done
+  configs=( $(ktx-list) )
+  if [ "${#configs[@]}" -eq 0 ]; then
+      echo "ERROR: No configs present in ${HOME}/.kube." 1>&2
+      return 1
+  fi
 
-      return
-    fi
+  # If no argument was given then list configs
+  if [ -z "${config}" ]; then
+    ktx-print-configs
+    return $?
+  fi
 
-    # If argument is "None" then unset the KUBECONFIG variable
-    if [[ "$1" == "none" ]] || [[ "$1" == "None" ]]; then
-        unset KUBECONFIG
-        return
-    fi
+  # If argument is "none" or "config" then unset the KUBECONFIG variable
+  if [ "${1,,}" = "none" -o "${config}" = "config" ]; then
+      unset KUBECONFIG
+      ktx-config
+      return $?
+  fi
 
-    # Verify config exists
-    if [ -e "${HOME}/.kube/${1}" ]; then
-        export KUBECONFIG="${HOME}/.kube/${1}"
-    else
-        echo "echo \"The following file does not exist: ${HOME}/.kube/${1}. Exiting...\""
-        return 1
-    fi
+  # Verify config exists
+  if [ -e "${HOME}/.kube/${1}" ]; then
+      export KUBECONFIG="${HOME}/.kube/${1}"
+  else
+      echo "ERROR: The file '${HOME}/.kube/${1}' does not exist" 1>&2
+      return 1
+  fi
 }
+
+###############################################################################################
+# completion
+
+_ktx() {
+       local cur=${COMP_WORDS[COMP_CWORD]}
+       COMPREPLY=( $(compgen -W "$(ktx-list) NONE" -- $cur) )
+}
+complete -F _ktx ktx
+complete -F _ktx ktx-config
